"""Add Message model for negotiations

Revision ID: 196eb485d9ac
Revises: 4e12c35c35d7
Create Date: 2026-02-11 01:47:31.480398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '196eb485d9ac'
down_revision = '4e12c35c35d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_checkouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('bargain_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('checkout_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bargain_id'], ['bargain_sessions.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('disputes')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    op.create_table('disputes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dispute_type', sa.VARCHAR(length=20), server_default=sa.text("'order'::character varying"), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resolution', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('farmer_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('farmer_response_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('farmer_evidence', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('buyer_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('buyer_response_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('buyer_evidence', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filer_id'], ['users.id'], name='disputes_filer_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='disputes_order_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name='disputes_target_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disputes_pkey'),
    sa.UniqueConstraint('ticket_id', name='disputes_ticket_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('pending_checkouts')
    # ### end Alembic commands ###
