"""add bargain_id to orders

Revision ID: 5c2785cb9bfa
Revises: 2d9a268c2246
Create Date: 2026-02-08 07:25:07.175071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2785cb9bfa'
down_revision = '2d9a268c2246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bargain_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bargain_sessions', ['bargain_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bargain_id')

    # ### end Alembic commands ###
