"""add mpesa tracking to escrow

Revision ID: 7efc2370a9cc
Revises: ece1d4108040
Create Date: 2026-02-10 01:56:28.543750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7efc2370a9cc'
down_revision = 'ece1d4108040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['mpesa_receipt'])
        batch_op.create_unique_constraint(None, ['b2c_conversation_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escrow_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
