"""Fresh start for live postgres

Revision ID: b3779cc9c880
Revises: 
Create Date: 2026-02-13 07:13:06.963463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3779cc9c880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('animals', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('animals', 'farmer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('bargain_messages', 'sender_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'animal_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'buyer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'farmer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('buyers', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('buyers', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('escrow_records', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('escrow_records', 'order_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('farmers', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('farmers', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'livestock_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'buyer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'farmer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('reviews', 'order_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('reviews', 'target_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('wishlists', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('wishlists', 'animal_id',
               existing_type=sa.NUMERIC(),
               type_=app.models.UUIDType(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlists', 'animal_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('wishlists', 'user_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'target_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'order_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('orders', 'farmer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('orders', 'buyer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'livestock_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'receiver_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('messages', 'sender_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('farmers', 'user_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('farmers', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('escrow_records', 'order_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('escrow_records', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('buyers', 'user_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('buyers', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'farmer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'buyer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('bargain_sessions', 'animal_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('bargain_messages', 'sender_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('animals', 'farmer_id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('animals', 'id',
               existing_type=app.models.UUIDType(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
